var Constants = {
	'STATUS_GRAPH_IS_READY' : 888,
	'STATUS_DATA_OK' : 130,
	'STATUS_DATA_NO_NUMERIC' : 121,
	'STATUS_WRONG_TYPE_GRAPH' : 101,
	'STATUS_NO_TYPE_GRAPH' : 102,
}

module.exports = Constants;